"""
Keyword-based market categorization for ShockTest.

Classifies each market title into: politics, sports, crypto,
entertainment, science, or other.

No API keys required — runs instantly.

Usage:
    python analysis/categorize.py
    python analysis/categorize.py --force   # re-categorize all
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from analysis.helpers import get_db

VALID_CATEGORIES = {
    "politics", "elections", "geopolitics", "sports", "esports",
    "crypto", "finance", "tech", "science", "culture",
    "weather", "other",
}

# Keyword lists — checked in priority order (first match wins).
# More specific categories MUST come before broader ones.
_KEYWORDS: dict[str, list[str]] = {
    # --- Specific categories first ---
    "esports": [
        " lol ",
        "league of legends",
        "dota",
        "valorant",
        "counter-strike",
        " csgo ",
        " cs2 ",
        "overwatch",
        "fortnite",
        "apex legends",
        " lec ",
        " lck ",
        " lpl ",
        " vct ",
        " esl ",
        " iem ",
        "esport",
        "e-sport",
        " bo3 ",
        " bo5 ",
        "natus vincere",
        " navi ",
        "fnatic",
        "g2 esports",
        "t1 ",
        "cloud9",
        "team liquid",
        "faze clan",
    ],
    "weather": [
        "hurricane",
        "tornado",
        "earthquake",
        "wildfire",
        "flood",
        "drought",
        "heat wave",
        "heatwave",
        "cold snap",
        "snowfall",
        "blizzard",
        "cyclone",
        "typhoon",
        "storm",
        "rainfall",
        "temperature record",
        "hottest",
        "coldest",
        "category 5",
        "el nino",
        "la nina",
        "weather",
        "noaa",
    ],
    "crypto": [
        "bitcoin",
        " btc ",
        "ethereum",
        " eth ",
        "crypto",
        "blockchain",
        "defi",
        "nft",
        "solana",
        " sol ",
        "dogecoin",
        "doge",
        " xrp ",
        "ripple",
        "binance",
        " bnb ",
        "cardano",
        " ada ",
        "avalanche",
        " avax ",
        "polygon",
        " matic ",
        "chainlink",
        " ltc ",
        "stablecoin",
        " usdc ",
        " usdt ",
        "tether",
        "altcoin",
        "memecoin",
        " dao ",
        "web3",
        "layer 2",
        "layer2",
        " l2 ",
        "base chain",
        "arbitrum",
        "optimism",
        "uniswap",
        " token ",
        " coin ",
    ],
    "finance": [
        "stock",
        "s&p 500",
        " s&p ",
        "nasdaq",
        "dow jones",
        " spy ",
        " qqq ",
        "treasury",
        "bond yield",
        "yield curve",
        " ipo ",
        "earnings",
        "revenue",
        "market cap",
        "share price",
        "bull market",
        "bear market",
        "recession",
        "gdp ",
        " cpi ",
        "unemployment",
        "jobs report",
        "nonfarm",
        "payroll",
        "forex",
        " usd ",
        " eur ",
        "gold price",
        "oil price",
        "crude oil",
        " wti ",
        "brent",
        "commodity",
        "hedge fund",
        "wall street",
        "berkshire",
        "federal reserve",
        "fed rate",
        "interest rate",
        "rate cut",
        "rate hike",
        "inflation",
        "deflation",
        "bank of america",
        "jpmorgan",
        "goldman",
        "citadel",
    ],
    "elections": [
        "election",
        "ballot",
        "primary",
        "caucus",
        "midterm",
        "runoff",
        "electoral college",
        "electoral vote",
        "swing state",
        "will win the",
        "nominee",
        "nomination",
        "presidential race",
        "senate race",
        "gubernatorial",
        "house seat",
        "redistrict",
        "gerrymandering",
        "voter turnout",
        "polling",
        "approval rating",
    ],
    "geopolitics": [
        "ukraine",
        "russia",
        "iran",
        "gaza",
        "hamas",
        "hezbollah",
        "israel",
        "yemen",
        "houthi",
        "taiwan strait",
        "south china sea",
        "north korea",
        " nato ",
        "ceasefire",
        "invasion",
        " coup ",
        "sanctions",
        "tariff",
        "trade war",
        "missile",
        "airstrike",
        "strike ",
        "nuclear weapon",
        "weapons",
        "peace deal",
        "peace agreement",
        "un resolution",
        "un vote",
        "security council",
        "g7 ",
        "g20",
        "diplomatic",
        "embassy",
        "refugee",
        "annex",
        "occupation",
        "territory",
        "border conflict",
        "military",
        " war ",
        "belgium",
        "countries",
    ],
    "politics": [
        "trump",
        "biden",
        "harris",
        "obama",
        "clinton",
        "desantis",
        "newsom",
        "pelosi",
        "mcconnell",
        "schumer",
        "zelensky",
        "putin",
        "xi jinping",
        "modi",
        "macron",
        "scholz",
        "sunak",
        "trudeau",
        "netanyahu",
        "vote",
        "senate",
        "congress",
        "republican",
        "democrat",
        "gop",
        "white house",
        "oval office",
        "president",
        "vice president",
        "governor",
        "mayor",
        "legislation",
        "bill passes",
        "filibuster",
        "impeach",
        "indicted",
        "conviction",
        "verdict",
        "supreme court",
        "executive order",
        "cia",
        "fbi",
        "doj",
        "sec ",
        "policy",
        "partisan",
        "bipartisan",
    ],
    "tech": [
        "ai ",
        " ai,",
        "artificial intelligence",
        "machine learning",
        "gpt",
        "chatgpt",
        "openai",
        "anthropic",
        "llm",
        "model release",
        "apple",
        "google",
        "microsoft",
        "amazon",
        "meta ",
        "nvidia",
        "tesla",
        "spacex",
        "startup",
        "silicon valley",
        "semiconductor",
        "chip",
        "quantum computing",
        "autonomous",
        "self-driving",
        "robot",
        "iphone",
        "android",
        "software",
        "app store",
        "cloud computing",
        "data center",
        "cybersecurity",
        "hack ",
        "breach",
        "encryption",
    ],
    "science": [
        "nasa",
        "space",
        "rocket",
        "mars",
        "moon landing",
        "asteroid",
        "vaccine",
        "cancer",
        "fda",
        "drug trial",
        "clinical trial",
        "covid",
        "pandemic",
        "virus",
        "outbreak",
        "quantum",
        "fusion",
        "nuclear",
        "cern",
        "discovery",
        "experiment",
        "research study",
        "climate",
        "emission",
        "carbon",
        "renewable",
        "species",
        "genome",
        "crispr",
    ],
    "culture": [
        "oscar",
        "academy award",
        "emmy",
        "grammy",
        "golden globe",
        "box office",
        "movie",
        "film",
        "album",
        "song",
        "billboard",
        "spotify",
        "streaming",
        "netflix",
        "disney",
        "hbo",
        "taylor swift",
        "beyonce",
        "kanye",
        "drake",
        "celebrity",
        "viral",
        "tiktok",
        "youtube",
        "instagram",
        "podcast",
        "reality tv",
        "concert",
        "tour",
        "social media",
        "influencer",
        "meme",
        "trending",
    ],
    "sports": [
        " nfl ",
        " nba ",
        " mlb ",
        " nhl ",
        " mls ",
        " ufc ",
        " f1 ",
        "super bowl",
        "world cup",
        "world series",
        "stanley cup",
        "champions league",
        "premier league",
        "la liga",
        "bundesliga",
        "serie a",
        "ligue 1",
        "playoffs",
        "grand slam",
        "wimbledon",
        "us open",
        "french open",
        "australian open",
        "pga",
        "soccer",
        "football",
        "basketball",
        "baseball",
        "hockey",
        "tennis",
        "golf",
        "boxing",
        "mma",
        "wrestling",
        "rugby",
        "cricket",
        "cycling",
        "formula 1",
        "motogp",
        "kentucky derby",
        "quarterback",
        "touchdown",
        "hat trick",
        "patriots",
        "lakers",
        "warriors",
        "cowboys",
        "chiefs",
        "eagles",
        "celtics",
        "bucks",
        "nuggets",
        "knicks",
        "nets",
        "suns",
        "yankees",
        "dodgers",
        "astros",
        "mets",
        "cubs",
        "braves",
        "manchester",
        "arsenal",
        "chelsea",
        "liverpool",
        "barcelona",
        "madrid",
        "bayern",
        "psg",
        "juventus",
        "red sox",
        "blue jays",
        "phillies",
        "reds",
        "rangers",
        "athletics",
        "angels",
        "padres",
        "royals",
        "orioles",
        "guardians",
        "nationals",
        "marlins",
        "rockies",
        "diamondbacks",
        "brewers",
        "cardinals",
        "pirates",
        "twins",
        "tigers",
        "white sox",
        "rays",
        "mariners",
        "grizzlies",
        "76ers",
        "cavaliers",
        "pacers",
        "hawks",
        "raptors",
        "pistons",
        "wizards",
        "hornets",
        "magic",
        "timberwolves",
        "pelicans",
        "thunder",
        "blazers",
        "spurs",
        "kings",
        "clippers",
        "wolves",
        "bulls",
        "flyers",
        "red wings",
        "penguins",
        "bruins",
        "canadiens",
        "hurricanes",
        "panthers",
        "devils",
        "islanders",
        "oilers",
        "flames",
        "canucks",
        "jets",
        "senators",
        "predators",
        "blue jackets",
        "blackhawks",
        "kraken",
        "wild",
        "avalanche",
        "stars",
        "ducks",
        "sharks",
        "sabres",
        "capitals",
        "lightning",
        "maple leafs",
        "golden knights",
        "illini",
        "hawkeyes",
        "fighting ",
        "pigossi",
        "zavatska",
        "colsanitas",
        "copa ",
        " o/u ",
        "spread:",
        " vs. ",
        " vs ",
    ],
}


def categorize_market(question: str) -> str:
    """
    Classify a prediction market question by keyword matching.

    Checks each category's keyword list in priority order:
    crypto → sports → politics → entertainment → science → other.

    Args:
        question: The market title/question string.

    Returns:
        One of: politics, sports, crypto, entertainment, science, other.
    """
    # Pad with spaces so boundary-padded tokens (e.g. " eth ") match at start/end
    text = " " + question.lower() + " "

    for category, keywords in _KEYWORDS.items():
        for kw in keywords:
            if kw in text:
                return category

    return "other"


def categorize_all_markets(force: bool = False) -> None:
    """
    Categorize all uncategorized markets in market_series by keyword matching.

    Updates both market_series (category field) and all matching
    shock_events documents. Runs instantly — no API calls.

    Args:
        force: If True, re-categorize markets that already have a category.
    """
    db = get_db()

    # Only categorize markets that have shock events
    shock_market_ids = set(db["shock_events"].distinct("market_id"))
    base_query: dict = {"market_id": {"$in": list(shock_market_ids)}}
    if not force:
        base_query["category"] = None
    markets = list(db["market_series"].find(base_query, {"market_id": 1, "question": 1}))

    if not markets:
        print("All markets already categorized. Use --force to re-run.")
        return

    print(f"Categorizing {len(markets)} markets...")

    for i, market in enumerate(markets):
        question = market["question"]
        category = categorize_market(question)

        db["market_series"].update_one(
            {"_id": market["_id"]},
            {"$set": {"category": category}},
        )
        db["shock_events"].update_many(
            {"market_id": market["market_id"]},
            {"$set": {"category": category}},
        )

        print(f"  [{i + 1}/{len(markets)}] {category:15s} | {question[:60]}")

    # Print category summary
    print("\nCategory breakdown:")
    pipeline = [{"$group": {"_id": "$category", "count": {"$sum": 1}}}, {"$sort": {"count": -1}}]
    for doc in db["shock_events"].aggregate(pipeline):
        print(f"  {doc['_id'] or 'uncategorized':20s}: {doc['count']} shocks")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Categorize shock markets by keyword")
    parser.add_argument("--force", action="store_true", help="Re-categorize already-categorized markets")
    args = parser.parse_args()
    categorize_all_markets(force=args.force)
